type MockAttachmentRecord = {
  filename: string;
  contentType: string;
  body: string;
};

const KNOWN_MOCK_ATTACHMENTS: Record<string, MockAttachmentRecord> = {
  "att-1846-1": {
    filename: "corrected-invoice.pdf",
    contentType: "application/pdf",
    body: `%PDF-1.1
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Count 1 /Kids [3 0 R] >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>
endobj
4 0 obj
<< /Length 72 >>
stream
BT
/F1 18 Tf
72 720 Td
(Mock corrected invoice attachment for demo mode) Tj
ET
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000010 00000 n 
0000000064 00000 n 
0000000121 00000 n 
0000000199 00000 n 
trailer
<< /Root 1 0 R /Size 5 >>
startxref
322
%%EOF`
  },
  "mail-att-1": {
    filename: "Q1-Metrics-Report.pdf",
    contentType: "application/pdf",
    body: `%PDF-1.1
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Count 1 /Kids [3 0 R] >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>
endobj
4 0 obj
<< /Length 64 >>
stream
BT
/F1 18 Tf
72 720 Td
(Mock Q1 support metrics report for demo mode) Tj
ET
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000010 00000 n 
0000000064 00000 n 
0000000121 00000 n 
0000000199 00000 n 
trailer
<< /Root 1 0 R /Size 5 >>
startxref
314
%%EOF`
  }
};

function isGeneratedMockAttachmentId(attachmentId: string) {
  return (
    attachmentId.includes("-att-") ||
    attachmentId.startsWith("mail-send-") ||
    attachmentId.startsWith("msg-")
  );
}

export function resolveMockAttachment(attachmentId: string): MockAttachmentRecord | null {
  const known = KNOWN_MOCK_ATTACHMENTS[attachmentId];
  if (known) {
    return known;
  }

  if (!isGeneratedMockAttachmentId(attachmentId)) {
    return null;
  }

  return {
    filename: `mock-attachment-${attachmentId}.txt`,
    contentType: "text/plain; charset=utf-8",
    body: `Mock attachment\n\nID: ${attachmentId}\n\nThis file was generated by the 6esk sample-data layer so attachment downloads work in UI demo mode.`
  };
}
